<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-Worker-b58e2a67-ca15-4c5f-ad96-b25f7352ced9</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Agents.AI" Version="1.0.0" />
        <PackageReference Include="Microsoft.Agents.AI.OpenAI" Version="1.0.0" />
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="11.0.0-preview.2.26159.112" />
        <PackageReference Include="OllamaSharp" Version="5.4.25" />
        <PackageReference Include="OpenAI" Version="2.9.1" />
    </ItemGroup>
</Project>
