### Create a conversation
POST {{baseUrl}}/conversations

> {%
    client.global.set("conversationId", response.body.conversationId);
%}

### Send message to conversation
POST {{baseUrl}}/conversations/{{conversationId}}/messages
Content-Type: application/json

{
  "text": "notify me when Metallica plays in Stockholm"
}
